# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_ingredients',
            name='name_of_ingredient',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maj_ingredients',
            name='name_of_ingredient',
            field=models.CharField(choices=[('veg', 'Vegetable'), ('fruit', 'Fruit')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
